apiVersion: v1
kind: PersistentVolume
metadata:
  name: es-pv
  namespace: elk
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /data/es
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: es-pv-claim
  namespace: elk
  labels:
    app: es
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
