apiVersion: v1
data:
  kibana.yml: |
    server.port: 5601
    server.host: "0.0.0.0"
    elasticsearch.hosts: "http://es-kibana.elk.svc.cluster.local:9200"
    elasticsearch.username: ${ELASTICSEARCH_USER}
    elasticsearch.password: ${ELASTICSEARCH_PASSWORD}
      #elasticsearch:
      #  username: elastic
      #  password: "123456"
    kibana.index: ".kibana"
kind: ConfigMap
metadata:
  name: kibana-config
  namespace: elk
