apiVersion: v1
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    xpack.monitoring.elasticsearch.hosts: http://es-kibana.elk.svc.cluster.local:9200
    xpack.monitoring.elasticsearch.username: "elastic" 
    xpack.monitoring.elasticsearch.password: "Aa123456"
kind: ConfigMap
metadata:
  name: logstash-yml-config
  namespace: elk
